# Generated by Django 4.2.6 on 2023-10-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testimonial',
            unique_together=set(),
        ),
    ]
